from .models import Book

BOOKS: dict[int, Book] = {
    1: Book(
        id=1,
        mission_name="Artemis Lunar Landing",
        commander="Lovell",
        mission_type="surface",
        description="Crewed lunar landing attempt.",
        phase="active",
        priority=1,
        launch_date="2026-09-01",
    ),
    2: Book(
        id=2,
        mission_name="Mars Rover Deployment",
        commander="Vasquez",
        mission_type="surface",
        description="Deploy a rover on the Martian surface.",
        phase="launch",
        priority=2,
        launch_date="2027-03-15",
    ),
    3: Book(
        id=3,
        mission_name="Orbital Telescope",
        commander="Kranz",
        mission_type="orbital",
        description="Deploy a deep-field space telescope.",
        phase="planning",
        priority=3,
        launch_date=None,
    ),
    4: Book(
        id=4,
        mission_name="EVA Repair Walk",
        commander="Lovell",
        mission_type="eva",
        description="Extra-vehicular activity to repair the array.",
        phase="active",
        priority=1,
        launch_date="2026-08-30",
    ),
    5: Book(
        id=5,
        mission_name="Deep Space Probe",
        commander="Vasquez",
        mission_type="deep_space",
        description="Launch a probe to the outer system.",
        phase="complete",
        priority=2,
        launch_date="2025-11-10",
    ),
    6: Book(
        id=6,
        mission_name="Surface Habitat Build",
        commander="Kranz",
        mission_type="surface",
        description="Assemble the lunar surface habitat.",
        phase="archived",
        priority=4,
        launch_date=None,
    ),
}
